version: "1"
services:
  # База данных
  db:
    image: dgraph/standalone:v21.03.2
    container_name: editor-db
    volumes:
      - ~/dgraph:/dgraph
    network_mode: host
  # Сервер
  svc:
    build: ./editorsvc
    container_name: editor-svc
    network_mode: host
    depends_on:
      - "db"
  # Веб-клиент
  web:
    build: ./editor-web-app
    container_name: editor-web-app
    network_mode: host
