version: "3"
services:
  # База данных
  db:
    image: dgraph/standalone:v21.03.2
    container_name: editor-db
    volumes:
      - ~/dgraph:/dgraph
    ports:
      - "9080:9080"
    networks:
      - app-network
  # Сервер
  svc:
    build: ./editorsvc
    container_name: editor-svc
    ports:
      - "9001:9000"
    networks:
      - app-network
  # Веб-клиент
  web:
    build: ./editor-web-app
    container_name: editor-web-app
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
