version: "3"
services:
  # База данных zero (https://dgraph.io/docs/deploy/dgraph-zero/)
  editor-db-zero:
    image: dgraph/dgraph:v22.0.0
    volumes:
      - /tmp/data:/dgraph
    restart: on-failure
    command: dgraph zero --my=editor-db-zero:5080
    networks:
      - app-network
  # База данных alpha (https://dgraph.io/docs/deploy/dgraph-alpha/)
  editor-db-alpha:
    image: dgraph/dgraph:v21.03.2
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=editor-db-alpha:7080 --zero=editor-db-zero:5080 --security whitelist=172.0.0.0/8
    networks:
      - app-network
  # Сервер
  svc:
    build: ./editorsvc
    container_name: editor-svc
    ports:
      - "9001:9000"
    networks:
      - app-network
  # Веб-клиент
  web:
    build: ./editor-web-app
    container_name: editor-web-app
    ports:
      - "3000:80"
    networks:
      - app-network

  s3:
    image: minio/minio:latest
    ports:
        - "127.0.0.1:9099:9099"
        - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - storage-minio:/data
    command: server --address "0.0.0.0:9099" --console-address ":9000" /data
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  storage-minio:
    external: true
