export enum ActionType {
  LeftMouseClick = 1,
  LeftMouseDown,
  LeftMouseUp,
  LeftMouseDoubleClick,
  RightMouseClick,
  RightMouseDown,
  RightMouseUp,
  RightMouseDobleClick,
  KeyClick,
  KeyDown,
  KeyUp,
  KeyWithMod,
  Drag,
  WheelUp,
  WheelDown,
  WheelClick,
  Pause
}

export enum ActionGroup {
  Mouse,
  Keyboard,
  Pause,
  Tick,
  Other
}

// https://docs.microsoft.com/ru-ru/dotnet/api/system.windows.forms.keys?view=windowsdesktop-6.0
// https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values
export const CODE_BY_WINDOWS_KEY: Record<string, string> = {
  A: "KeyA",
  B: "KeyB",
  C: "KeyC",
  D: "KeyD",
  E: "KeyE",
  F: "KeyF",
  G: "KeyG",
  H: "KeyH",
  I: "KeyI",
  J: "KeyJ",
  K: "KeyK",
  L: "KeyL",
  M: "KeyM",
  N: "KeyN",
  O: "KeyO",
  P: "KeyP",
  Q: "KeyQ",
  R: "KeyR",
  S: "KeyS",
  T: "KeyT",
  U: "KeyU",
  V: "KeyV",
  W: "KeyW",
  X: "KeyX",
  Y: "KeyY",
  Z: "KeyZ",
  D0: "Digit0",
  D1: "Digit1",
  D2: "Digit2",
  D3: "Digit3",
  D4: "Digit4",
  D5: "Digit5",
  D6: "Digit6",
  D7: "Digit7",
  D8: "Digit8",
  D9: "Digit9",
  NumPad0: "Numpad0",
  NumPad1: "Numpad1",
  NumPad2: "Numpad2",
  NumPad3: "Numpad3",
  NumPad4: "Numpad4",
  NumPad5: "Numpad5",
  NumPad6: "Numpad6",
  NumPad7: "Numpad7",
  NumPad8: "Numpad8",
  NumPad9: "Numpad9",
  OemMinus: "Minus",
  OemPlus: "Equal",
  Oem1: "Semicolon",
  Oem3: "Backquote",
  Oem5: "Backslash",
  Oem6: "BracketRight",
  OemOpenBrackets: "BracketLeft",
  OemQuotes: "Quote",
  OemComma: "Comma",
  OemPeriod: "Period",
  OemQuestion: "Slash",
  Back: "Backspace",
  LeftCtrl: "ControlLeft",
  LeftAlt: "AltLeft",
  LeftShift: "ShiftLeft",
  LWin: "MetaLeft",
  RightCtrl: "ControlRight",
  RightAlt: "AltRight",
  RightShift: "ShiftRight",
  RWin: "MetaRight",
  Return: "Enter",
  Capital: "CapsLock",
  Next: "PageDown",
  Up: "ArrowUp",
  Down: "ArrowDown",
  Left: "ArrowLeft",
  Right: "ArrowRight"
};
