export enum MutationTypes {
  SET_SCRIPTS_INFO = "SET_SCRIPTS_INFO",
  SET_SCRIPT = "SET_SCRIPT",
  UPDATE_SCRIPT = "UPDATE_SCRIPT",
  SELECT_FRAME = "SELECT_FRAME",
  DELETE_SCRIPT = "DELETE_SCRIPT",
  CONFIGURE_PATH = "CONFIGURE_PATH"
}
