export enum MutationTypes {
  SET_SCRIPTS_INFO = "SET_SCRIPTS_INFO",
  SET_SCRIPT = "SET_SCRIPT",
  UPDATE_FRAMES = "UPDATE_FRAMES",
  SELECT_FRAME = "SELECT_FRAME",
  CONFIGURE_PATH = "CONFIGURE_PATH"
}
